services:
  api:
    build:
      dockerfile: api.Dockerfile
    environment:
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY:-}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY:-}
      - PORT=${PORT:-3081}
      - HOST=${HOST:-0.0.0.0}
      - API_HOST=${API_HOST:-http://localhost:3081}
  frontend:
    build:
      dockerfile: frontend.Dockerfile
    ports:
        - "3081:80"
    links:
        - api