services:
  api:
    build:
      dockerfile: api.Dockerfile
    environment:
      - RECAPTCHA_SITE_KEY=${RECAPTCHA_SITE_KEY:-}
      - RECAPTCHA_SECRET_KEY=${RECAPTCHA_SECRET_KEY:-}
      - PORT=${PORT:-3081}
      - HOST=${HOST:-0.0.0.0}
      - API_HOST=${API_HOST:-http://localhost:3081}
    ports:
      - "${PORT:-3081}:${PORT:-3081}"
    dns:
      - 1.1.1.1
      - 8.8.8.8